kind: pipeline
type: kubernetes
name: CI

trigger:
  branch:
    - main
  event:
    - pull_request
    - push

environment:
  NODE_VER: node:22.3.0-slim

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.pnpm-store
  - name: install
    image: $NODE_VER
    commands:
      - corepack enable
      - pnpm config set store-dir .pnpm-store
      - pnpm i
  - name: lint
    image: $NODE_VER
    commands:
      - corepack enable
      - pnpm lint
  - name: typecheck
    image: $NODE_VER
    commands:
      - corepack enable
      - pnpm typecheck
  - name: build
    image: $NODE_VER
    commands:
      - corepack enable
      - pnpm build
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./.pnpm-store

volumes:
- name: cache
  host:
    path: /tmp/pnpm_cache
